title: 40tude
description: "40tude.fr, mon blog perso. Au programme : Rust, Python, C++, assembleur (algorithmes, tutos, cr√©ation d'OS...), administration Windows/Linux, un peu de maths, sans oublier mes notes de pilotage moto sur circuit." 

theme: just-the-docs

# url: https://40tude.github.io/
url: https://www.40tude.fr

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Read https://just-the-docs.com/docs/ui-components/code/line-numbers/
# Turn on line numbers for fenced code blocks globally
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Disable the HTML minifier that breaks linenos markup
compress_html:
  ignore:
    envs: all

# Footer last edited timestamp
last_edit_timestamp: false # It is set to false because I have my own footer show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

favicon_ico: "/assets/images/40tude.png"
lang: fr


back_to_top: true
back_to_top_text: "Back to top"

callouts_level: quiet # or loud
callouts:
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  highlight:
    color: yellow

              
ga_tracking: G-HEDHH8MLQE
ga_tracking_anonymize_ip: true

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - docs/billet00.md
  - docs/billet01.md
  - docs/categorie_02/
  - docs/categorie_03/
  - scrap_book/
  # - docs/maths/
  # - .sass-cache/
  # - .jekyll-cache/
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
  # # specific to the theme website:
  # - bin/
  # - lib/
  # - "*.gemspec"
  # - "*.gem"
  # - package.json
  # - package-lock.json
  # - Rakefile
  # - CODE_OF_CONDUCT.md
  # - docker-compose.yml
  # - Dockerfile
  # # theme test code
  # - fixtures/