[package]
name = "titanic"
version = "0.1.0"
edition = "2024"

[dependencies]
linfa = "0.7"
linfa-logistic = "0.7"
# linfa-datasets = "0.7"
ndarray = "0.15"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
